name: Deploy to Google Cloud Run


on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true


      - name: Authorize Docker push to Google Container Registry
        run: gcloud auth configure-docker


      - name: Build and Push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-angular-app:$GITHUB_SHA .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-angular-app:$GITHUB_SHA


      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-angular-app \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-angular-app:$GITHUB_SHA \
          --platform managed \
          --region europe-west1 \
          --allow-unauthenticated
